### PR TITLE
csv upload: do not import contributor roles without names or form source or type without a form value

### LINKED ISSUE #4071: descriptive metadata spreadsheet: ignore contributor role data if contributor name not provided
When importing a descriptive metadata spreadsheet, if any of the cells include data for 

`event*.contributor*.role*.code` 

and 

`event*.contributor*.role*.value` 

but do not include a name for the corresponding contributor in 

`event*.contributor*.role*.name.value`

then do not import the `event*.contributor*.role*.code` and `event*.contributor*.role*.value` metadata into the Cocina. 

The presence of contributor role metadata without a contributor name in the Cocina leads to errors when trying to publish the druid. Fixing such errors is a complex remediation task.

Related HB error: https://app.honeybadger.io/projects/50568/faults/89158658

**Example spreadsheet data that will cause a problem**

In the example below, the data from the second row will result in errors at the publish step.

event1.contributor1.name1.value | event1.contributor1.role1.code | event1.contributor1.role1.value
-- | -- | --
Schmidt, Heinrich | dfd | Defendant
  | dfd | Defendant

### LINKED ISSUE #4072: descriptive metadata spreadsheet: ignore form.type and/or form.source if form.value not provided
When importing a descriptive metadata spreadsheet, if any of the cells include data for 

`form*.type` 

and 

`form*.source.value` 

but do not include a corresponding value for

`form*.value`

then do not import the `form*.type` and `form*.source.value` metadata into the Cocina. 

The presence of `form.source` and/or `form.type` metadata without a corresponding `form.value` in the Cocina prevents a druid from being indexed. This makes it very difficult to understand the processing status of the druid and creates a complex remediation task to fix the Cocina.

Related HB error: https://app.honeybadger.io/projects/49898/faults/95491637

**Example spreadsheet data that will cause a problem**

In the example below, data imported from both rows will result in indexing errors. Both druids have one problem in common:

`form4.source.value` and `form4.type` have data but there's no column for `form4.value` - compare with the data for the `form3.*` fields, which have three columns.

Additionally, the second row has two more problems:

1. `form1.type` has data but `form1.value` is empty
2. `form2.type` has data but `form2.value` is empty

form1.type | form1.value | form2.type | form2.value | form3.source.value | form3.type | form3.value | form4.source.value | form4.type | form5.type | form5.value
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
genre | Record of proceedings | genre | Transcript | MODS resource types | resource type | text | MODS resource types | resource type | extent | 60 pages
genre |   | genre |   | MODS resource types | resource type | mixed material | MODS resource types | resource type | extent | 233 pages

### PR DESCRIPTION
**Pull request by ndushay**
~~HOLD for PO approval (Andrew)~~

# Why was this change made? 🤔

Fixes #4071
Fixes #4072

Contributors with roles but not name are basically invalid and require complex remediation (error when publishing).  
Form data without a value (e.g. it just has source or type, but no value) also require complex remediation (prevents indexing)

I've created sul-dlss/cocina-models/issues/610 for cocina validation of contributors

# How was this change tested? 🤨

Andrew reviewed it in stage;  also specs.

⚡ ⚠ If this change has cross service impact (including writing to shared file systems or interacting with other SDR APIs), ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

⚡ ⚠ If this change updates the Argo UI, run all integration tests that use Argo and create a PR on the integration test repo to fix anything this change breaks. ⚡

# Does your change introduce accessibility violations? 🩺

Nope!

⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the WCAG A or AA conformance levels); if it does, include a rationale. See the [Infrastructure accessibility guide](https://github.com/sul-dlss/DeveloperPlaybook/blob/main/best-practices/infra-accessibility.md) for more detail. ⚡

### CODE REVIEW

File: spec/services/description_import_spec.rb [hunk 1]
```diff
@@ -8,160 +8,160 @@
...
-      			"value": "Converted from MARCXML to MODS version 3.7 using MARC21slim2MODS3-7_SDR_v2-5.xsl (SUL 3.7 version 2.5 20210421; LC Revision 1.140 20200717)",
-      			"type": "record origin"
-      		}],
-      		"identifier": [{
-      			"value": "a111",
-      			"type": "SIRSI"
-      		}]
-      	},
-      	"purl": "https://sul-purl-stage.stanford.edu/bb041bm1345"
+        "title": [{
```
Comment (ndushay) [inline spec/services/description_import_spec.rb:11]: this part is just formatting (how did we end up with so smay spaces??

File: spec/services/description_import_spec.rb [hunk 2]
```diff
@@ -256,4 +256,433 @@
...
+        end
+
+        it "has the expected value" do
+          expect(updated.value!.to_h).to eq expected.to_h
+        end
+      end
+    end
+  end
+
+  context "with form property" do
```
Comment (ndushay) [inline spec/services/description_import_spec.rb:494]: the form tests start here.

File: app/services/description_import.rb [hunk 3]
```diff
@@ -89,4 +95,36 @@ def compact_params(params)
...
   end
+
+  def remove_contributors_if_role_without_name(compacted_params_hash)
+    return unless compacted_params_hash && compacted_params_hash[:contributor]
+
+    compacted_params_hash[:contributor].each do |contributor|
+      next unless contributor && contributor[:name].nil? && contributor[:role].present?
+
+      compacted_params_hash[:contributor].delete(contributor)
+    end
```
Comment (mjgiarlo) [inline app/services/description_import.rb:106]: I *believe* Ruby already has an iterator that does this. Would you consider:

```suggestion
    compacted_params_hash[:contributor].delete_if do |contributor|
      contributor && contributor[:name].nil? && contributor[:role].present?
    end
```

❓

File: app/services/description_import.rb [hunk 4]
```diff
@@ -89,4 +95,36 @@ def compact_params(params)
...
+  end
+
+  def remove_form_if_source_without_value(compacted_params_hash)
+    return unless compacted_params_hash && compacted_params_hash[:form]
+
+    compacted_params_hash[:form].each do |form|
+      next unless form && form[:value].nil? && (form[:source].present? || form[:type].present?)
+
+      compacted_params_hash[:form].delete(form)
+    end
```
Comment (mjgiarlo) [inline app/services/description_import.rb:116]: Same as above: consider `delete_if` if that's the use case for `each` here.

File: app/services/description_import.rb [hunk 5]
```diff
@@ -89,4 +95,36 @@ def compact_params(params)
...
+  end
+
+  def remove_nested_attributes_without_value(compacted_params_hash)
+    # event can have contributors, geographic can have form
```
Comment (mjgiarlo) [inline app/services/description_import.rb:120]: Should this comment also say something about `relatedResource`?

File: app/services/description_import.rb [hunk 6]
```diff
@@ -89,4 +95,36 @@ def compact_params(params)
...
+    [:relatedResource, :event, :geographic].each do |parent_property|
+      next if compacted_params_hash[parent_property].blank?
```
Comment (mjgiarlo) [inline app/services/description_import.rb:122]: Are we protecting against `nil`s or empty arrays or both or something else here?

File: spec/services/description_import_spec.rb [hunk 7]
```diff
@@ -256,4 +256,433 @@
...
+        title: [{value: "my great contributor"}],
+        purl: "https://purl/jr825qh8124"
+      }.tap do |h|
+        h[:contributor] = [expected_contributor] if expected_contributor
+      end
+    end
+    let(:expected) { Cocina::Models::Description.new(expected_hash) }
+
+    [nil, "Someone"].each do |name|
+      context "when role as code, name: '#{name}'" do
```
Comment (mjgiarlo) [inline spec/services/description_import_spec.rb:275]: I'm having trouble English-ing this. Can you help translate?

File: app/services/description_import.rb (hunk 6 above)
Comment (ndushay) [reply app/services/description_import.rb:122]: we only care to process if there is a (parent_property) present in the hash.  It could also be worded:

```next unless compacted_params_hash[parent_property].present?``` 

and I had it that way, but it seemed more confusing.

Yes - we are protecting against nil and also empty arrays.  It all depends on what columns are in the spreadsheet, at this point.

File: spec/services/description_import_spec.rb (hunk 7 above)
Comment (ndushay) [reply spec/services/description_import_spec.rb:275]: a role can be represented as a code or a value (or maybe a URI).    Doesn't everyone know that?

I will try to clarify.

File: app/services/description_import.rb (hunk 3 above)
Comment (ndushay) [reply app/services/description_import.rb:106]: great suggestion;  done.

File: app/services/description_import.rb (hunk 4 above)
Comment (ndushay) [reply app/services/description_import.rb:116]: also done.

File: app/services/description_import.rb (hunk 5 above)
Comment (ndushay) [reply app/services/description_import.rb:120]: done

**Review by aaron-collier — APPROVED** [review]

**Comment by ndushay** [comment]
tagging @justinlittman because I _just_ noticed there is a DescriptionValidator service in Argo.   I think, per the tickets, I was not supposed to reject the csv, but just ignore these oddities ... but would welcome your review and wonder if this now working-code-wins solution is contrary to a design I didn't see.

**Comment by justinlittman** [comment]
I defer to @andrewjbtw on desired behavior.
