### PR TITLE
Restore bulk job deletion functionality

### LINKED ISSUE #1882: Restore Delete button functionality for bulk_jobs
**Describe the bug**
In the bulk_jobs view, each row in the jobs table has a Delete button that doesn't do anything.

**User Impact**
Fixes non-functioning button

**To Reproduce**
1. Go to https://argo-stage.stanford.edu/apos/druid:qc410yz8746/bulk_jobs
2. Click on the **Delete** button for any of the jobs
3. Click the confirmation **Delete** button in the modal
4. Displays error page "The page you were looking for doesn't exist."

**Expected behavior**
Users shouldn't get confused about a non-functioning button in Argo

**Screenshots**
Screen Shot 2020-03-31 at 12 34 30 PM

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by mjgiarlo**
Fixes #1882

## Why was this change made?

To restore functionality that was inadvertently removed years ago but is still useful.

## Was the documentation (README, DevOpsDocs, wiki, consul, etc.) updated?

No.

## Does this change affect how this application integrates with other services?

No.

### CODE REVIEW

File: config/routes.rb [hunk 1]
```diff
@@ -84,6 +84,7 @@
         get 'status_help'
         get 'help'
         get ':time/log', action: :show, as: 'show'
+        delete '', action: :delete
```
Comment (jcoyne) [inline config/routes.rb:87]: Could this just be `:destroy` on the containing resource?

Comment (mjgiarlo) [reply config/routes.rb]: Was already working on that, ha! New commit just pushed.

Comment (jcoyne) [reply config/routes.rb]: No, I see the difficulty, a delete would imply deleting one with an ID, but this is the bulk job for the apo.

File: config/routes.rb [hunk 2]
```diff
@@ -79,12 +79,12 @@
   end
 
   resources :apos, only: [] do
+    resource :bulk_jobs, only: :destroy
```
Comment (jcoyne) [inline config/routes.rb:82]: Great solution!
