### PR TITLE
[HOLD] Use cocina properties in bulk action -> register druids

### LINKED ISSUE #3526: Update bulk action registration to use cocina properties
The bulk action registration form (available in the bulk actions menu under "Register Druids" in the CSV section) is still tied to how the registration form worked two years ago, meaning it does not include:

- the new Cocina access rights properties
- reading order for image and book content types
- barcode

It also uses spaces in the headers and I think while we're updating the headers we should also spell out abbreviations, go all lower-case, and use `_` instead of spaces.

New headers:

- administrative_policy_object (required)
- collection (optional)
- initial_workflow (required)
- content_type (required)
- reading_order (required if "content_type" is "book" or "image")
- source_id (required)
- catkey (optional)
- barcode (optional)
- label (required unless a catkey has been entered)
- rights_view (required)
- rights_download (required)
- rights_location (required if "view" or "download" uses "location-based")
- project_name (optional)
- tags (optional, may repeat)

For validation, I think we are currently doing row-by-row reporting to the log. I'd like to test this after the new headers are in place to see what's being returned when errors occur. The reporting I would like:

- a downloadable CSV of the druids successfully registered 
  - already implemented, should continue to function the same way (including the same columns)
- reporting to the log which rows failed
  - since failure on this job means that no druid will have been assigned yet, include the source id in the error message

### PR DESCRIPTION
**Pull request by aaron-collier**
## Why was this change made? 🤔

Closes #3526 

Requires review/testing by @andrewjbtw 

New field list displayed:

Screen Shot 2022-04-26 at 1 22 42 PM

## How was this change tested? 🤨

Updated unit test.

⚡ ⚠ If this change has cross service impact (including writing to shared file systems or interacting with other SDR APIs), ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

⚡ ⚠ If this change updates the Argo UI, run all integration tests that use Argo and create a PR on the integration test repo to fix anything this change breaks. ⚡

### CODE REVIEW

File: app/services/registration_csv_converter.rb [hunk 1]
```diff
@@ -86,4 +90,27 @@ def dro_type(content_type)
...
+  def access(row)
+    {}.tap do |access|
+      access[:view] = row.fetch('rights_view')
+      access[:download] = row.fetch('rights_download')
+      access[:location] = row.fetch('rights_location') if [access[:view], access[:download]].include?('location-based')
+      access[:controlledDigitalLending] = controlled_digital_lending(access)
+    end
+  end
+
+  def controlled_digital_lending(access)
```
Comment (jcoyne) [inline app/services/registration_csv_converter.rb:110]: Should this method end with a `?`

**Review by jcoyne — CHANGES_REQUESTED** [review]

File: app/services/registration_csv_converter.rb [hunk 2]
```diff
@@ -86,4 +90,27 @@ def dro_type(content_type)
...
+      structural[:hasMemberOrders] = [{ viewingDirection: row['reading_order'] }] if row['reading_order'].present?
+    end
+  end
+
+  def access(row)
+    {}.tap do |access|
+      access[:view] = row.fetch('rights_view')
+      access[:download] = row.fetch('rights_download')
+      access[:location] = row.fetch('rights_location') if [access[:view], access[:download]].include?('location-based')
+      access[:controlledDigitalLending] = controlled_digital_lending?(access)
```
Comment (jcoyne) [inline app/services/registration_csv_converter.rb:106]: This doesn't seem right.  It's not automatically CDL if stanford/none.  But it should optionally allow CDL to be set if these preconditions are met.

**Review by jcoyne — CHANGES_REQUESTED** [review]

File: app/services/registration_csv_converter.rb (hunk 2 above)
Comment (aaron-collier) [reply app/services/registration_csv_converter.rb:106]: @jcoyne Suggestions on a field or how to handle that? I was basing this on https://github.com/sul-dlss/argo/blob/223ef77fa4f559387d4973d568132f5523968245/app/services/cocina_dro_access.rb which uses `rights == 'cdl-stanford-nd'` do set controlledDigitalLending to true, but I don't see anything going the other way.

Comment (aaron-collier) [reply app/services/registration_csv_converter.rb:106]: Perhaps @andrewjbtw can weigh in on how he may prefer to pass in CDL via the spreadsheet.

Comment (andrewjbtw) [reply app/services/registration_csv_converter.rb:106]: Could we cover this with an optional column in the CSV for `rights_controlledDigitalLending`? But I would like to avoid making people enter "false" when they don't want CDL. It's such an exceptional status that I'd like to set things up so people only indicate when it's "true".

That could mean:

- only require the column for CDL if one of the items on the spreadsheet will have "true"
- if the column is present and the cell for a particular row is blank, treat that as "false"
- if the column is present and the cell for a particular row has "true", set CDL
- if the column is present and all cells are blank, treat that as "false"

Comment (andrewjbtw) [reply app/services/registration_csv_converter.rb:106]: And to be explicit, the "view:stanford" and "download:none" must also be set to be valid for CDL.

Comment (aaron-collier) [reply app/services/registration_csv_converter.rb:106]: I think an optional column with `view:stanford` and `download:none` validation would be fine. :+1:

**Review by jcoyne — CHANGES_REQUESTED** [review]
Please add a test where rights_controlledDigitalLending is set.

**Comment by aaron-collier** [comment]
@jcoyne tests added.

**Review by jcoyne — APPROVED** [review]

**Comment by jcoyne** [comment]
Whomever merges, please squash these commits.

**Comment by ndushay** [comment]
whoops - another PR merged with [HOLD] in the title
