### PR TITLE
Remove symphony links.

### LINKED ISSUE #4289: Removing a Folio HRID from a druid should also remove any corresponding catkey that may still be there
**Describe the bug**
When a user removes a Folio HRID from a druid, it moves the previous Folio HRID to "previous folio". But if the item also still has a catkey, it leaves the catkey behind. This means the catkey still gets published to the public XML, which means that it's still treated in Access systems like it has a catkey. That in turn, prevents some updates from going through, such as changes to SW release status.

Example: https://argo.stanford.edu/view/wz486hk4528

This item had a Folio HRID but it was recently removed. The Cocina now shows:

```
"catalogLinks": [
      {
        "catalog": "previous folio",
        "refresh": false,
        "catalogRecordId": "a11760291"
      },
      {
        "catalog": "symphony",
        "refresh": true,
        "catalogRecordId": "11760291"
      }
    ],
```
In the past, moving an identifier from "folio" to "previous folio" would move the corresponding "symphony" to "previous symphony". We could still do that. Or we could remove the catkey completely since the "previous folio" tracks the information. What we can't do is leave the catkey in place.

**User Impact**
This has a subtle but noticeable effect on how things appear in SW, including in some cases preventing items from appearing in SW at all.

**To Reproduce**
It doesn't look like this can be reproduced in stage because there are no more catkeys there.

1. Go to an item with a catkey and Folio HRID
2. Remove the Folio HRID
3. See the catkey is left behind

**Expected behavior**
Removing an HRID should remove a corresponding catkey.

**Additional context**
I wonder if we removed the syncing code that used to handle this.

Also, before anyone asks, removing all the catkeys will require coordination with the Access portfolio. So I think it's better in the short run to address this issue rather than wait for a mass cleanup.

### PR DESCRIPTION
**Pull request by justinlittman**
closes #4289

# Why was this change made?

Keeping symphony links is causing mayhem in access systems.

# How was this change tested?
Unit

### CODE REVIEW

File: app/services/catalog_record_id.rb [hunk 1]
```diff
@@ -98,7 +103,7 @@ def find_not(type)
   end
 
   def find(type)
```
Comment (justinlittman) [inline app/services/catalog_record_id.rb:105]: I found it confusing that some find methods returned catalog record ids and others returned catalog records. This normalizes to returning catalog records.

File: app/services/catalog_record_id.rb [hunk 2]
```diff
@@ -43,10 +43,14 @@ def type
...
     end
+
+    def other_type
+      'symphony'
+    end
   end
 
   def self.links(model)
-    new(model).links
+    new(model).links.map(&:catalogRecordId)
```
Comment (jmartin-sul) [inline app/services/catalog_record_id.rb:53]: i found it a little confusing that this class method `links` does the `.map(&:catalogRecordId)`, but instance method `links` doesn't.

**Review by jmartin-sul — APPROVED** [review]
comment about one thing that i found confusing, but otherwise makes sense to me, and unit test change looks good, so ✅

File: app/services/catalog_record_id.rb (hunk 2 above)
Comment (jmartin-sul) [reply app/services/catalog_record_id.rb:53]: ah, i see that the same is true for the instance and class method versions of `other_links`, so at least it's consistently inconsistent 🙂, and keeps from breaking an interface with the rest of the codebase, so that makes sense too.

also weird, now that i think about it, that some class methods are defined using the `class << self` approach, and others the `self.` approach, but that's not something i'd ask to see changed in this PR, since this PR didn't introduce that.
