### PR TITLE
Display an error when there is a bad cocina fetch

### LINKED ISSUE #2306: Instead of "network error" show a descriptive message when a modal won't load because of a Cocina issue
**Describe the bug**
When an item doesn't have a valid Cocina representation, certain actions will pop up a window with a message that just says "Network error". These actions are:

- the "Set rights" blue button
- clicking on a file in the file list (under contents) to download a file

Since the issue isn't really a network error, show a message that indicates that it is related to Cocina.

**User Impact**
Users are blocked from the tasks they are trying to do, and are shown a misleading message. To the extent possible, a message like "network error" should be reserved for when there is a real network connection problem.

**To Reproduce**
I've made an object with a non-valid source id on stage for testing:
https://argo-stage.stanford.edu/view/druid:qv217cy9963

1. Go to the example item above
2. Click on "set rights" or try to download "testfile.txt"
3. See a window pop up with the message "network error".

**Expected behavior**
If the Cocina representation is the problem, the error message should indicate that.

**Screenshots**
This is the only message people see for this error:
Screen Shot 2020-11-03 at 12 29 54 PM

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made?

Fixes #2306

## How was this change tested?
Tested on stage
Screen Shot 2020-12-03 at 4 40 19 PM

### CODE REVIEW

**Review by peetucket — APPROVED** [review]

**Comment by peetucket** [comment]
Janky test failure on CI?

File: app/controllers/items_controller.rb [hunk 1]
```diff
@@ -24,6 +24,13 @@ class ItemsController < ApplicationController
     set_governing_apo
   ]
 
+  rescue_from Dor::Services::Client::UnexpectedResponse do |exception|
+    md = /\((.*)\)/.match exception.message
+    detail = JSON.parse(md[1])['errors'].first['detail']
+    redirect_to solr_document_path(params[:id]),
+                flash: { error: "Unable to retrieve the cocina model: #{detail.truncate(200)}" }
+  end
+
```
Comment (ndushay) [inline app/controllers/items_controller.rb:33]: would it be better for the DSC to have a specific error for validation failures?  Presumably with the DSA also having a specific error for validation failures?  Could be a separate issue.

Comment (jcoyne) [reply app/controllers/items_controller.rb:33]: I'm not sure I understand DSC always returns UnexpectedResponse when there is a response that is not a 200 or 404 : https://github.com/sul-dlss/dor-services-client/blob/34645ee6759eeca7ff6191b8c40d478d4a7edc3c/lib/dor/services/client/object.rb#L52

DSA always returns an ErrorResponse model in these cases: https://github.com/sul-dlss/dor-services-app/blob/master/openapi.yml#L1023-L1034

Why only handle a subset of the errors when we can handle all of them?

**Review by justinlittman — APPROVED** [review]
