### PR TITLE
fix bug where tags were not making it during registration

### LINKED ISSUE #3650: Tags are not being added to newly registered items
**Describe the bug**
Tags are not being assigned to newly registered items, with the exception of the project tag. If you enter any tags in the "Tags" boxes on the registration form, they are not carried over to the druids being registered.

**User Impact**
Users have to go back and add tags later.

**To Reproduce**
1. Go to the registration form
2. Fill it out, including tags in the "Tags" box
3. Register
4. See that the druids do not have the tags from the Tags box. The Project tag (in the Project box) is being included, but not the other tags.

**Expected behavior**
Tags should be assigned to the new druids.

**Additional context**
This seems to have started this morning.

### PR DESCRIPTION
**Pull request by peetucket**
## Why was this change made? 🤔

Fixes #3650 - tags were not making it the object because the params being sent by javascript was "tag" and the params expected by the server were "tags" (started with changes made in https://github.com/sul-dlss/argo/pull/3637 )...I normalized to "tags" , which makes more sense.

## How was this change tested? 🤨

Localhost browser.  Updated integration tests to catch this in the future: https://github.com/sul-dlss/infrastructure-integration-test/pull/426

### CODE REVIEW

File: app/javascript/registration/register.js [hunk 1]
```diff
@@ -41,7 +41,7 @@ export default function DorRegistration(initOpts) {
       return document.getElementById('rights').value
     },
 
-    // Grab list of tags from the form and rejects blanks
+    // Grab list of tags from the form
```
Comment (peetucket) [inline app/javascript/registration/register.js:44]: it's not rejecting blanks anymore!  they get rejected on the server now

**Review by jcoyne — CHANGES_REQUESTED** [review]
Can you write a feature spec for this? We should be able to register an item with tags and show them on the page.

**Review by jcoyne — APPROVED** [review]

**Comment by jcoyne** [comment]
Feature test to come in another PR, to follow.
