### PR TITLE
fix population of item registration apo select box

### LINKED ISSUE #766: Register Items - Admin Policy pulldown is empty
related to solr 6.1 change I presume.

### PR DESCRIPTION
**Pull request by jmartin-sul**
also, cleaned up the code and wrote tests.

deployed to stage.  appears to be working, but would be good to get someone who knows their way around item registration better to take a look.  @LynnMcRae or @blalbrit?

for the reviewers, i tried to break things into logical commits, and to do something similar to PR #760.

also, FWIW, the solr query requests now look something like this, according to the logs:
```
https://[host]/argo_stage/select?wt=ruby&q=apo_register_permissions_ssim:"sunetid:apanopte"+OR+apo_register_permissions_ssim:"workgroup:sdr:administrator-role"+OR+apo_register_permissions_ssim:"workgroup:dlss:lyberteam"+OR+apo_register_permissions_ssim:"workgroup:dlss:developers"&fq=objectType_ssim:adminPolicy&fq=!tag_ssim:"Project+:+Hydrus"&rows=99999&fl=id,tag_ssim,dc_title_tesim&start=0
```

closes #766

### CODE REVIEW

File: spec/helpers/registration_helper_spec.rb [hunk 1]
```diff
@@ -1,7 +1,38 @@
...
+    it 'sorts the results and formats them correctly' do
+      result_rows = [
+        {'id' => 1, 'tag_ssim' => 'prefix : suffix', 'dc_title_tesim' => 'z'},
+        {'id' => 2, 'tag_ssim' => 'AdminPolicy : default', 'dc_title_tesim' => 'y'},
+        {'id' => 3, 'tag_ssim' => 'prefix : suffix2', 'dc_title_tesim' => 'x'}
+      ]
+      expect(Dor::SearchService).to receive(:query).and_return(double(docs: result_rows))
+
+      apos = apo_list(perm_keys)
+      expect(apos).to eq [['y', '2'], ['x', '3'], ['z', '1']]
```
Comment (jmartin-sul) [inline spec/helpers/registration_helper_spec.rb]: i prefer it as-is, but would be willing to change this if others would rather follow hound's suggestion.  but i find this much more readable than the suggestion for this particular situation.
