### PR TITLE
bypass jqgrid column selector and just implement in plain html checkboxes

### LINKED ISSUE #1670: In report view, unable to select columns
**Describe the bug**
In Argo, I navigate to: `https://argo.stanford.edu/report?f%5Bnonhydrus_apo_title_ssim%5D%5B%5D=ETDs&f%5Bprocessing_status_text_ssi%5D%5B%5D=Accessioned&f%5Breleased_to_ssim%5D%5B%5D=Searchworks`, and I select view > report view. Next, I select `columns` so I can specify the columns I want in my report. Nothing happens: no column labels appear in a dropdown menu so that I can select the ones I want.

**User Impact**
The columns are preset (at least they were in the past), so that all columns are not included when I download a report -- if I do nothing to specify which columns I want to see in the report. This limits my ability to perform robust analysis on a group of items. This is an important feature to maintain. I use this feature several times a month for various tasks.

**To Reproduce**
1. Go to 'https://argo.stanford.edu/report?f%5Bnonhydrus_apo_title_ssim%5D%5B%5D=ETDs&f%5Bprocessing_status_text_ssi%5D%5B%5D=Accessioned&f%5Breleased_to_ssim%5D%5B%5D=Searchworks'
2. Click on `Select View`
3. Select `Report View`
4. In bottom left-hand corner, select `Columns`
5. Nothing happens. I should see a drop down menu display with a list of all available columns that I can select from.

**Expected behavior**
Please see the above description, which explains the expected behavior.

**Screenshots**
This behavior is self explanatory.

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by peetucket**
fixes #1670 

## Why was this change made?

* jquery update broke our usage of column selectors built into jqgrid
* initial attempts at updating jqgrid were not successful

This replicates the functionality for downloading of reports without the use of jqgrid.  It does not allow for dynamic column selection for display on the screen, but that was deemed not important (downloading is more important).

Todo:
- [x] validate approach
- [x] improve UI/styling

### CODE REVIEW

File: app/javascript/packs/report.js [hunk 1]
```diff
@@ -65,8 +61,11 @@ $(document).ready(function() {
     title: "Download as CSV",
     buttonicon: 'ui-icon-disk',
     onClickButton() {
-      const visible = $.grep($('#report_grid').jqGrid('getGridParam','colModel'), (col,idx) => (col.name !== 'rn') && !col.hidden);
-      const field_list = $.map(visible, (col,idx) => col.name).join(',');
+      var selected_columns = [];
+      $.each($("input[name='selected_columns']:checked"), function(){
```
Comment (jcoyne) [inline app/javascript/packs/report.js]: I think the original `map` is easier to read than an `each`

**Comment by jcoyne** [comment]
This works for me.  I think we need to write a test for this.   Ideally we make this a Stimulus controller so that we can encapsulate the functionality.

File: app/javascript/packs/report.js [hunk 2]
```diff
@@ -52,11 +52,7 @@ $(document).ready(function() {
     caption: "Columns",
     title: "Choose Columns",
     buttonicon: 'ui-icon-script',
-    onClickButton() { return $('#report_grid').jqGrid('columnChooser', {
-      done(stuff) { return (
-        this.resize()
-      ); }
-    }); }
+    onClickButton() { $('#column_selector').toggleClass('hidden'); }
```
Comment (jcoyne) [inline app/javascript/packs/report.js]: We don't need to involve jQuery here:
`document.getElementById('column_selector').classLIst.toggle('hidden')`
