### PR TITLE
apo_form: fix Default Object Rights

### LINKED ISSUE #3135: Edit APO form should show the current rights in the rights menu
**Describe the bug**
The Edit APO form contains a rights menu that should display the currently selected defaultObjectRights on that APO. For certain rights values, it is showing "world" instead of the current value.

See the SDR Graveyard: https://argo.stanford.edu/apo/druid:kg712km1576/edit

The defaultObjectRights are dark. But the Edit APO form shows "world".

**User Impact**
Saving the form saves the currently selected rights. The result is that if you go to the edit form to make an unrelated change and don't notice that the rights are set incorrectly, saving the form will save the wrong rights. This happened to me in that the SDR Graveyard briefly got switched to world rights instead of dark.

**To Reproduce**
1. Go to  https://argo.stanford.edu/apo/druid:kg712km1576
2. See that the rights (in Cocina and XML) are dark
3. Open the Edit form
4. See the menu show "world" selected

**Expected behavior**
The current value should be selected on the menu.

**Additional context**
Moving to the new UI for APO editing will limit the impact of issues like this. The pencil-based edits will mean opening fewer fields at once for editing.

### PR DESCRIPTION
**Pull request by ndushay**
## Why was this change made? 🤔

Fixes #3135

### Before

in Edit APO form, Default Rights always shows "world", regardless of what is in APO 

image

### After

Default Rights associated with the APO are displayed

image

## How was this change tested? 🤨

updated Argo feature spec (a flaky one, sadly) and deployed to QA and tested there.

No cross service impact or Argo UI changes ... the fix ensures we display the CORRECT value

⚡ ⚠ If this change has cross service impact, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

⚡ ⚠ If this change updates the Argo UI, run all integration tests that use Argo and create a PR on that repo to fix anything this change breaks. ⚡

### CODE REVIEW

File: app/forms/apo_form.rb [hunk 1]
```diff
@@ -101,22 +101,16 @@ def options_for_use_license_type(current_value)
     end.compact # the options block will produce nils for unused deprecated entries, compact will get rid of them
   end
 
-  def default_object_rights
-    return default_rights if model.nil?
-
-    check_default_object_rights || default_rights
-  end
-
-  def check_default_object_rights
```
Comment (ndushay) [inline app/forms/apo_form.rb:110]: My assessment is that this was split into 2 methods to avoid a rubocop complaint about complexity.   However, my head just about broke trying to figure out if "check_xxx" should return a boolean or a string, and combining the methods resulted in fewer lines and cleaner code, IMO.

File: app/forms/apo_form.rb [hunk 2]
```diff
@@ -101,22 +101,16 @@ def options_for_use_license_type(current_value)
...
+    return default_rights if default_access.nil?
+    return 'cdl-stanford-nd' if default_access.controlledDigitalLending
 
     access = default_access.access
-
     return "loc:#{default_access.readLocation}" if access == 'location-based'
-    return 'cdl-stanford-nd' if default_access.controlledDigitalLending
     return "#{access}-nd" if default_access.download == 'none' && access.in?(%w[stanford world])
+
+    access || default_rights
```
Comment (ndushay) [inline app/forms/apo_form.rb:113]: This line is what fixed the bug.  Essentially, this method was NOT returning the value unless it was in one of the special cases covered by return statements ... so then the form was using "default_rights" which is set in the constructor to be "world".

File: spec/features/apo_spec.rb [hunk 3]
```diff
@@ -44,9 +45,9 @@
     select 'View', from: 'permissionRole'
     click_button 'Add'
 
-    page.select('Attribution Share Alike 3.0 Unported', from: 'Default use license')
-
-    page.select('accessionWF', from: 'apo_form_default_workflows')
+    select('Dark (Preserve Only)', from: 'Default Object Rights')
```
Comment (ndushay) [inline spec/features/apo_spec.rb:48]: Let's not default to world rights for this test.

File: spec/features/apo_spec.rb [hunk 4]
```diff
@@ -44,9 +45,9 @@
     select 'View', from: 'permissionRole'
     click_button 'Add'
 
-    page.select('Attribution Share Alike 3.0 Unported', from: 'Default use license')
```
Comment (ndushay) [inline spec/features/apo_spec.rb:47]: let's not explicitly use `page.select` as the `page` part is implied.

File: spec/features/apo_spec.rb [hunk 5]
```diff
@@ -55,7 +56,9 @@
     expect(page).to have_text 'created'
 
     click_on 'Edit APO'
+    expect(page).to have_text 'Add group' # wait for form to render
     expect(find_field('Title').value).to eq('APO Title')
+    expect(find_field('Default Object Rights').value).to eq('dark')
```
Comment (ndushay) [inline spec/features/apo_spec.rb:61]: and now we check to make sure the Edit APO form displays the correct value.

File: spec/features/apo_spec.rb [hunk 6]
```diff
@@ -74,13 +77,17 @@
...
     fill_in 'Default Copyright statement', with: 'New copyright statement'
     fill_in 'Default Use and Reproduction statement', with: 'New use statement'
     select 'Attribution No Derivatives 3.0 Unported', from: 'Default use license'
     click_button 'Update APO'
+    expect(page).to have_text 'Actions' # wait for form to render
 
     click_on 'Edit APO'
+    expect(page).to have_text 'Add group' # wait for form to render
     expect(find_field('Title').value).to eq('New APO Title')
+    expect(find_field('Default Object Rights').value).to eq('stanford')
```
Comment (ndushay) [inline spec/features/apo_spec.rb:90]: and now this worked on jcoyne's laptop, but not mine.  I gave up and hope circleci works.

File: app/forms/apo_form.rb [hunk 7]
```diff
@@ -35,7 +35,7 @@ def initialize(model, search_service:)
   def populate_from_model
     self.title = model.description.title.first.value
     self.agreement_object_id = model.administrative.hasAgreement
-    self.default_rights = default_object_rights
```
[the remark this answers is not in the document]
Comment (mjgiarlo) [reply app/forms/apo_form.rb:38]: @ndushay I think this is a Fedora datastream vestige, as this info used to be stored canonically in the APO `defaultObjectRights` DS. Good change. 😄

File: app/forms/apo_form.rb (hunk 1 above)
Comment (mjgiarlo) [reply app/forms/apo_form.rb:110]: To my mind, this change makes it easier to figure out what's doing what in this class. Thank you!

File: app/forms/apo_form.rb [hunk 8]
```diff
@@ -101,22 +101,16 @@ def options_for_use_license_type(current_value)
...
-  end
-
-  def check_default_object_rights
-    default_access = model.administrative&.defaultAccess
-
-    return if default_access.nil?
+  def default_access
+    default_access = model&.administrative&.defaultAccess
+    return default_rights if default_access.nil?
+    return 'cdl-stanford-nd' if default_access.controlledDigitalLending
```
Comment (mjgiarlo) [inline app/forms/apo_form.rb:107]: Moving this up makes sense to me.

File: app/forms/apo_form.rb (hunk 2 above)
Comment (mjgiarlo) [reply app/forms/apo_form.rb:113]: @ndushay Interesting. So... in the bug case, `access` here would be ... `nil`?

**Comment by ndushay** [comment]
This particular test was flaky before I changed it.  I tried to make it less flaky, but I don't think I succeeded.  :-(

**Comment by ndushay** [comment]
Andrew has tested this in QA, and it is good to be merged when green.

**Review by mjgiarlo — APPROVED** [review]

**Comment by mjgiarlo** [comment]
Feel free to merge once CI finishes. 👏🏻
