### PR TITLE
Validate cell values for csv desc metadata spreadsheets

### LINKED ISSUE #3444: Descriptive upload validation: Validate cell values
For both individual and bulk upload:
* When cell value is #NA, #REF!, #VALUE?, or #NAME?, report "Value error: #{druid} has spreadsheet formula error in #{header}."
* When cell value is 0, report "Value error: #{druid} has 0 value in #{header}."

refs #3375

### PR DESCRIPTION
**Pull request by peetucket**
## Why was this change made? 🤔

Fixes #3444 - validates cell values in spreadsheet for 0s and spreadsheet errors.

## How was this change tested? 🤨

Added new tests

### CODE REVIEW

File: app/services/description_validator.rb [hunk 1]
```diff
@@ -14,13 +14,24 @@ def initialize(csv, bulk_job: false)
...
       validate_druid_rows
     end
     errors.empty?
   end
 
+  def validate_cell_values
+    @csv.each.with_index(2) do |row, i|
+      @headers.excluding('druid').each do |header|
+        location = row['druid'] || "row #{i}"
+        errors << "Value error: #{location} has 0 value in #{header}." if row[header] == '0'
```
Comment (peetucket) [inline app/services/description_validator.rb:29]: the ticket tells us to add the druid to the error message, but single object spreadsheets may not have a druid column...in which case, we will reference the row instead

File: app/services/description_validator.rb [hunk 2]
```diff
@@ -14,13 +14,24 @@ def initialize(csv, bulk_job: false)
...
+        errors << "Value error: #{location} has spreadsheet formula error in #{header}." if %w[#NA #REF! #VALUE? #NAME?].include? row[header]
+      end
```
Comment (peetucket) [inline app/services/description_validator.rb:31]: The ticket tells us to add the druid to the error message, but single object spreadsheets may not have a druid column, so we will use the row instead in that case.

**Review by jcoyne — APPROVED** [review]
