### PR TITLE
Switch call from load_instance to find

### LINKED ISSUE #1398: [argo/prod] NoMethodError: undefined method `load_instance' for Dor:Module
Did you mean?  load_dependency
## Backtrace

    line 118 of [PROJECT_ROOT]/app/models/track_sheet.rb: find_or_create_in_solr_by_id
    line 17 of [PROJECT_ROOT]/app/models/track_sheet.rb: block in generate_tracking_pdf
    line 17 of [PROJECT_ROOT]/app/models/track_sheet.rb: each

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49894/faults/49344322)

### PR DESCRIPTION
**Pull request by jcoyne**
Fixes #1398

### CODE REVIEW

File: app/models/track_sheet.rb [hunk 1]
```diff
@@ -40,6 +41,7 @@ def generate_tracking_sheet(druid, pdf)
     begin
       doc = find_or_create_in_solr_by_id(druid)
     rescue
+      byebug
```
Comment (aaron-collier) [inline app/models/track_sheet.rb]: Remove?

Comment (aaron-collier) [reply app/models/track_sheet.rb]: LOL, looks like you caught it while I was commenting.
