### PR TITLE
logging and status count improvements for failed job situations

### LINKED ISSUE #972: Background Release job too successful
A Release job for 6900 objects already has 10697 successes suggesting some replay or resubmission? a counting issue?  It may still be out there running. 

pastedimage

### PR DESCRIPTION
**Pull request by jmartin-sul**
* append to the log file when opening it instead of truncating it, so that log info from an unsuccessful job attempt isn't lost.
* zero out the success/failure/total druid counts before performing the job, in case this isn't the first time the job is being attempted for a bulk action, so that the job is incrementing fresh counts.

closes #972

### CODE REVIEW

File: app/jobs/release_object_job.rb [hunk 1]
```diff
@@ -20,7 +20,7 @@ def perform(bulk_action_id, params)
     @manage_release = params[:manage_release]
     @webauth = OpenStruct.new params[:webauth]
     @pids = params[:pids]
-    File.open(bulk_action.log_name, 'w') do |log|
+    with_bulk_action_log do |log|
```
Comment (jmartin-sul) [inline app/jobs/release_object_job.rb]: inclined to leave this, since i didn't change the line count, and i think i cleaned it up slightly overall.

File: app/jobs/descmetadata_download_job.rb [hunk 2]
```diff
@@ -11,8 +11,7 @@ class DescmetadataDownloadJob < GenericJob
   # requires `:pids` (an Array of pids) and output_directory
   def perform(bulk_action_id, params)
     zip_filename = generate_zip_filename(params[:output_directory])
-    initialize_counters(bulk_action)
-    File.open(bulk_action.log_name, 'w') do |log|
+    with_bulk_action_log do |log|
```
Comment (jmartin-sul) [inline app/jobs/descmetadata_download_job.rb]: inclined to leave this as-is for the same reason

Comment (tingulfsen) [inline app/jobs/descmetadata_download_job.rb]: Agreed.
