### PR TITLE
Filter out empty note from the spreadsheet upload

### LINKED ISSUE #5051: Cocina descriptive spreadsheet upload: drop note if no main value is present
(part of the work described in #5023 )

If a spreadsheet includes columns with a note subproperty but no corresponding main value, drop the note.

Example:

This spreadsheet ([type-without-value.csv](https://github.com/user-attachments/files/25540486/type-without-value.csv)) (exported from a prod item) contains multiple notes that have no values.

note1.displayLabel | note1.type | note2.displayLabel | note2.type | note3.displayLabel | note3.type
-- | -- | -- | -- | -- | --
Content note | content | Language note: Available languages | language | Source of document | reference

To reproduce/test: upload the spreadsheet to this item in stage: https://argo-stage.stanford.edu/view/druid:cr026zj9609

### PR DESCRIPTION
**Pull request by jcoyne**
# Why was this change made?
Fixes #5051

# How was this change tested?
ci

### CODE REVIEW

**Review by mjgiarlo — APPROVED** [review]

File: app/services/description_import_filter.rb [hunk 1]
```diff
@@ -47,6 +48,10 @@ def filter(compacted_params, model: Cocina::Models::Description)
 
   private
 
+  def remove_note_without_value(notes)
+    Array(notes).delete_if { !descriptive_value_sufficient?(it) }
```
Comment (jmartin-sul) [inline app/services/description_import_filter.rb]: TIL about `it`

**Review by jmartin-sul — APPROVED** [review]
