### PR TITLE
Disable publish/shelve in content metadata when setting rights to dark

### LINKED ISSUE #2220: Setting rights to "dark" in Argo is failing
**Describe the bug**
Setting an object's rights to "dark" is failing if any files in the object were previously published and/or shelved (i.e. there are files with "publish=yes" or "shelve=yes" in the contentMetadata).

Honeybadger error: https://app.honeybadger.io/projects/49894/faults/66958746

It looks like the system is validating that an item with rights set to dark does not have any shelved or published files. This is a good validation to have, but it will always fail if the system doesn't change the contentMetadata first when changing rights to dark. Users shouldn't be expected to edit the contentMetadata themselves to change the publish and shelve settings for all files, as that would require directly editing the XML. The act of setting rights to dark is supposed to apply contentMetadata changes automatically.

**User Impact**
It is not possible to set rights to dark via the set rights interface. This may result in delays in unpublishing purls. Time is usually a factor when purls are unpublished, since the most common reasons to set rights to dark are permissions or privacy issues, so a delay in applying these rights is a potentially serious problem.

**To Reproduce**
1. Go to an item in Argo that has 1) a published purl and 2) files available to access from the purl
2. Open the item for modification
3. Attempt to set rights to dark
4. The error will result in you being taken to the general library-status page
5. Check honeybadger

**Expected behavior**
Setting rights to dark should apply a change to the contentMetadata to set all files listed there to:

publish="no"
shelve="no"

This change should not affect the preserve status. That should remain "yes" or "no" according to how it was before the rights were set to dark.

**Additional context**
The expected behavior is how setting rights to dark has been applied since at least 2019, when I started at Stanford. Previously, when setting rights to dark, I'd see a corresponding change in the contentMetadata.

### PR DESCRIPTION
**Pull request by mjgiarlo**
Fixes #2220

## Why was this change made?

See #2220.

## How was this change tested?

CI

## Which documentation and/or configurations were updated?

None.

### CODE REVIEW

File: app/controllers/items_controller.rb [hunk 1]
```diff
@@ -214,7 +214,9 @@ def set_rights
     dro = object_client.find
     access_additions = CocinaAccess.from_form_value(params[:access_form][:rights])
     updated_access = dro.access.new(access_additions.value!)
-    updated = dro.new(access: updated_access)
+    structural_additions = CocinaStructural.from_form_value(params[:access_form][:rights], dro.structural)
+    updated_structural = dro.structural.new(structural_additions.value!)
```
Comment (jcoyne) [inline app/controllers/items_controller.rb:218]: Won't this raise an exception if rights is world?

Comment (mjgiarlo) [reply app/controllers/items_controller.rb:218]: I don't know. I was following the example above and leaning on the existing tests.

Comment (jcoyne) [reply app/controllers/items_controller.rb:218]: The existing test is only testing the set to dark case, so can you add a "set to stanford only" case?

Comment (mjgiarlo) [reply app/controllers/items_controller.rb:218]: I'll add a test case for sure.

Comment (mjgiarlo) [reply app/controllers/items_controller.rb:218]: @jcoyne also, isn't this a problem for the CocinaAccess stuff you added above? it can also return `None()`.

Comment (jcoyne) [reply app/controllers/items_controller.rb:218]: in the CocinaAccess case `None` is an error. The form should always return something sensible.

Comment (jcoyne) [reply app/controllers/items_controller.rb:218]: Yes, it's also a problem there. I'll work on that.

Comment (jcoyne) [reply app/controllers/items_controller.rb:218]: The `None` case never occurs on this update form. It's only used for registration. See https://github.com/sul-dlss/argo/pull/2224

Comment (mjgiarlo) [reply app/controllers/items_controller.rb]: Aha, I see. OK, I've updated the approach to stop using monads. Take another look?
