### PR TITLE
Moves Blacklight globably in Argo to communication with Solr over POS…

### LINKED ISSUE #321: when a user is in too many workgroups, they can't use Argo
more specifically, when the user is in too many workgroups that are recognized by argo (i.e. listed in .htaccess), and those workgroups are passed to the solr query that does permission checks.  when the query string is too long, the solr request fails, and the page loads that use that perm check (e.g. the front page) error out.

the error the user sees is `Sorry, I don't understand your search.` (@rosy1280 has a screenshot).

the error solr returns is:
```
RSolr::Error::Http: RSolr::Error::Http - 414 Request-URI Too Long
Error: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>414 Request-URI Too Large</title>
</head><body>
<h1>Request-URI Too Large</h1>
<p>The requested URL's length exceeds the capacity
limit for this server.<br />
</p>
</body></html>
```

the stack trace is:
```
Backtrace: /opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:284:in `adapt_response'
/opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:190:in `execute'
/opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:176:in `send_and_receive'
/opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/rsolr-ext-1.0.3/lib/rsolr-ext/client.rb:21:in `find'
/opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/bundler/gems/dor-services-764ce0f299b9/lib/dor/services/search_service.rb:74:in `query'
/opt/app/lyberadmin/argo/releases/20151208015719/app/models/user.rb:64:in `permitted_apos'
(irb):59:in `irb_binding'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/irb/workspace.rb:86:in `eval'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/irb/workspace.rb:86:in `evaluate'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/irb/context.rb:379:in `evaluate'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/irb.rb:489:in `block (2 levels) in eval_input'
	from /opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:284:in `adapt_response'
	from /opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:190:in `execute'
	from /opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:176:in `send_and_receive'
	from /opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/rsolr-ext-1.0.3/lib/rsolr-ext/client.rb:21:in `find'
	from /opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/bundler/gems/dor-services-764ce0f299b9/lib/dor/services/search_service.rb:74:in `query'
	from /opt/app/lyberadmin/argo/releases/20151208015719/app/models/user.rb:64:in `permitted_apos'
	from (irb):59
	from /opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/console.rb:110:in `start'
	from /opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/console.rb:9:in `start'
	from /opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:9:in `require'
	from bin/rails:9:in `<main>'
```
(stack trace is from the current develop branch of argo, though this was initially discovered in argo 2.x on prod)

you can reproduce by:
```ruby
test_user = User::find_or_create_by_remoteuser 'test_user' #don't need a real user, we'll fake webauth groups anyway
test_user_groups = (0..30).map { |num| "workgroup:workgroup_#{num}" }
test_user.set_groups_to_impersonate test_user_groups
test_user.permitted_apos
```

the same error occurs in the UI if you impersonate and don't enter anything, or if you have a huge search that's way too long for solr in the same way as the above.

one fix, at least for the too-many-workgroups problem, would be to have the request to solr be a post.  i'm not sure how much control we have over this, as i'm not sure whether the request type can be set by dor-services, or if that's farther down the stack and harder to access.

### LINKED ISSUE #355: Session hangs after Impersonate
In new stage today, press impersonate at top of page, enter just workgroup:dlss:developers and press Impersonate button. The session will not return and a new session hangs unless you clear your browsing data. This happened to me and was reproduced by DarrenH, both using Chrome.

### PR DESCRIPTION
**Pull request by mejackreed**
…T. This alleviates issues with GET URIs being too long. Also extracts permitted queries out of the User model into its own class.

This PR makes no assumptions about the logic contained in `#permitted_collections` and `#permitted_apos` but does test the POST functionality and output type.

Closes #321 Closes #355

### CODE REVIEW

File: app/models/concerns/permitted_queries.rb [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+    q = 'objectType_ssim:collection AND !project_tag_ssim:"Hydrus" '
+    q += permitted_apos.map {|pid| "#{SolrDocument::FIELD_APO_ID}:\"info:fedora/#{pid}\""}.join(' OR ') unless is_admin
+    result = solr_repository.search({:q => q, :rows => 1000, :fl => 'id,tag_ssim,dc_title_tesim'}).docs
+
+    # result = Dor::SearchService.query(q, :rows => 1000, :fl => 'id,tag_ssim,dc_title_tesim').docs
+    result.sort! do |a, b|
+      a['dc_title_tesim'].to_s <=> b['dc_title_tesim'].to_s
+    end
+
+    [['None', '']] + result.collect do |doc|
```
Comment (mejackreed) [inline app/models/concerns/permitted_queries.rb]: Ported over legacy code here.

Comment (mejackreed) [inline app/models/concerns/permitted_queries.rb]: Satisfying the :dog:
