### PR TITLE
Handle csv jobs missing druid column without repeating.

### LINKED ISSUE #3619: Do not retry a descriptive metadata bulk action that fails because of: RuntimeError: Column "druid" not found
Currently, if someone forgets to include a druid column on the descriptive CSV, the bulk action will get caught in an endless loop of retries with the error: `RuntimeError: Column "druid" not found`
https://app.honeybadger.io/projects/49894/faults/85168602

Since retrying cannot fix this error and it will apply to all rows, the job should fail and report the error back to the log so the user can see it.

### PR DESCRIPTION
**Pull request by justinlittman**
closes sul-dlss/dor-services-app#3619

## Why was this change made? 🤔
Avoid unnecessary job retries.

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact (including writing to shared file systems or interacting with other SDR APIs), ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

⚡ ⚠ If this change updates the Argo UI, run all integration tests that use Argo and create a PR on the integration test repo to fix anything this change breaks. ⚡

Unit

### CODE REVIEW

File: app/jobs/generic_job.rb [hunk 1]
```diff
@@ -134,11 +134,14 @@ def with_csv_items(csv, name:, druid_column: 'druid')
         cocina_object = Repository.find(druid)
         yield(cocina_object, csv_row, success, failure, row_num)
       rescue KeyError
-        raise "Column \"#{druid_column}\" not found"
+        raise
```
Comment (jcoyne) [inline app/jobs/generic_job.rb:137]: Can we just do `failure.call(...)` here? I think that would be easier to follow.

**Review by jcoyne — CHANGES_REQUESTED** [review]

File: app/jobs/generic_job.rb (hunk 1 above)
Comment (jcoyne) [reply app/jobs/generic_job.rb:137]: @justinlittman If this is for the whole sheet, can we validate it before making a background job (in the controller) and give instant feedback to the user?

Comment (justinlittman) [reply app/jobs/generic_job.rb:137]: Yes, but ticketed separately: https://github.com/sul-dlss/dor-services-app/issues/3971

Even if that is done, this is still necessary as backup as there is nothing that guarantees that this will be invoked with a csv with a druid column.

Comment (jcoyne) [reply app/jobs/generic_job.rb:137]: Can we just move the check to above the loop then?

Comment (justinlittman) [reply app/jobs/generic_job.rb]: Yes. Done.

**Review by jcoyne — APPROVED** [review]
