### PR TITLE
Rescue validation error in DescriptiveMetadataImportJob to avoid alerting honeybadger

### LINKED ISSUE #3478: Do not HB alert when ValidationError on DescriptiveMetadataImportJob
Currently, if a Cocina::Models::ValidationError is raised during a DescriptiveMetadataImportJob it logs the error and HB alerts. It should not HB alert.

```
2022-04-13 19:39:43 UTC Starting DescriptiveMetadataImportJob for BulkAction 307
Line 2: Line 2: Import descriptive metadata failed Cocina::Models::ValidationError Unrecognized types in description: description.contributor1.name1.structuredValue1 for druid:bb408qn5061 (2022-04-13 19:39:43 UTC)
2022-04-13 19:39:43 UTC Finished DescriptiveMetadataImportJob for BulkAction 307
```

## Backtrace

    line 22 of [PROJECT_ROOT]/app/jobs/descriptive_metadata_import_job.rb: block (2 levels) in perform
    line 21 of [PROJECT_ROOT]/app/jobs/descriptive_metadata_import_job.rb: block in perform
    line 135 of [PROJECT_ROOT]/app/jobs/generic_job.rb: block (2 levels) in with_csv_items

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49894/faults/84964957)

### PR DESCRIPTION
**Pull request by aaron-collier**
## Why was this change made? 🤔

Closes #3478 

This adds a pattern for filtering which jobs and error combinations will alert to honeybadger. 

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact (including writing to shared file systems or interacting with other SDR APIs), ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

⚡ ⚠ If this change updates the Argo UI, run all integration tests that use Argo and create a PR on the integration test repo to fix anything this change breaks. ⚡

### CODE REVIEW

File: app/jobs/generic_job.rb [hunk 1]
```diff
@@ -14,6 +14,9 @@
 class GenericJob < ApplicationJob
   # A somewhat easy to understand and informative time stamp format
   TIME_FORMAT = '%Y-%m-%d %H:%M%P'
+  DO_NOT_ALERT = {
+    'DescriptiveMetadataImportJob' => ['Cocina::Models::ValidationError']
```
Comment (jcoyne) [inline app/jobs/generic_job.rb:18]: How about rescuing this in the `DescriptiveMetadataImportJob` rather than add code to the base class just for the one subclass?

**Review by jcoyne — CHANGES_REQUESTED** [review]

File: app/jobs/generic_job.rb (hunk 1 above)
Comment (aaron-collier) [reply app/jobs/generic_job.rb:18]: @jcoyne,  I see that we already rescue in `DescriptiveImport` (https://github.com/sul-dlss/argo/blob/17cef1d40cde1f2c0521be6f0ceca65e863c9038/app/services/description_import.rb#L28) and that bubbles up into `GenericJob` where the alert is sent... 

I'm not clear on how to avoid the HB alert, which I think but could be wrong, is rescued in https://github.com/sul-dlss/argo/blob/main/app/jobs/generic_job.rb#L136 with the `failure.call` at https://github.com/sul-dlss/argo/blob/main/app/jobs/descriptive_metadata_import_job.rb#L23

Should I refactor the error path and remove the `failure.call` in `DescriptiveImportJob`? Or will that impact the failure count reporting?

Thanks.

Comment (jcoyne) [reply app/jobs/generic_job.rb:18]: There is no way for that rescued error to "bubble up".  It must have been from a different location.  Don't remove the failure.call, or you won't get proper counts.

Comment (jcoyne) [reply app/jobs/generic_job.rb:18]: It's the `cocina_object.new(description: description)` that is raising the error, not the DescriptionImport

Comment (aaron-collier) [reply app/jobs/generic_job.rb]: Done. Thanks.

File: app/jobs/descriptive_metadata_import_job.rb [hunk 2]
```diff
@@ -19,7 +19,14 @@ def perform(bulk_action_id, params)
       next failure.call('Not authorized') unless ability.can?(:update, cocina_object)
 
       DescriptionImport.import(csv_row: csv_row).either(
-        ->(description) { Repository.store(cocina_object.new(description: description)) && success.call('Successfully updated') },
+        lambda { |description|
+          begin
+            Repository.store(cocina_object.new(description: description))
+            success.call('Successfully updated')
+          rescue Cocina::Models::ValidationError => e
+            failure.call(e)
```
Comment (jcoyne) [inline app/jobs/descriptive_metadata_import_job.rb:27]: This should be `e.message`

**Review by jcoyne — CHANGES_REQUESTED** [review]

File: app/jobs/descriptive_metadata_import_job.rb (hunk 2 above)
Comment (aaron-collier) [reply app/jobs/descriptive_metadata_import_job.rb]: done.

**Comment by aaron-collier** [comment]
@jcoyne done.

**Review by jcoyne — APPROVED** [review]
