### PR TITLE
Align validation spreadsheet job with upload validation

### LINKED ISSUE #4372: Validate descriptive cocina spreadsheet bulk action should catch duplicate column errors
**Describe the bug**
If you upload a spreadsheet with duplicate column headers to the validate cocina bulk action, it does not report an error.

If you try to upload a descriptive cocina spreadsheet with duplicate column headers to the bulk action that actually tries to update the metadata, that action does report an error. 

The validation bulk action and the bulk action to change metadata should be consistent with each other.

**User Impact**
Users trust that passing the validation bulk action should mean that the upload will succeed and then are surprised when it does not.

**To Reproduce**
1. Go to argo-stage
2. Go to bulk actions
3. Choose validate descriptive metadata spreadsheet
4. Validate this spreadsheet: [descriptive-vp824kj1914-duplicate-columns.csv](https://github.com/sul-dlss/argo/files/14764558/descriptive-vp824kj1914-duplicate-columns.csv)
5. See no error
6. Now go to "Upload descriptive metadata spreadsheet" and upload the same spreadsheet
7. See error for duplicate columns: `Duplicate column headers: The header title1.value should occur only once.`

**Expected behavior**
The validation bulk action logic should match the import logic.

**Additional context**
The `Duplicate column headers` error also happens when trying to upload the same spreadsheet directly to the item. It's only the validation bulk action that doesn't catch the issue.

### PR DESCRIPTION
**Pull request by aaron-collier**
# Why was this change made?

Fixes #4372

# How was this change tested?

### CODE REVIEW

File: spec/requests/bulk_actions/validate_cocina_descriptive_jobs_spec.rb [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+      params = { 'csv_file' => fixture_file_upload('bulk_upload_descriptive.csv', 'text/csv') }
+
+      expect do
+        post '/bulk_actions/validate_cocina_descriptive_job', params:
+      end.to have_enqueued_job(ValidateCocinaDescriptiveJob)
+        .with(Integer, { csv_file: String })
+      expect(response).to have_http_status(:see_other)
+    end
+
+    context 'when dupolicate columns in csv' do
```
Comment (mjgiarlo) [inline spec/requests/bulk_actions/validate_cocina_descriptive_jobs_spec.rb:40]: Typo: `dupolicate` (though maybe it's a word in Italian I haven't learned yet 🤌)

**Review by mjgiarlo — APPROVED** [review]
One teensy typo but otherwise :shipit:
