### PR TITLE
add the Registration datetime to the report columns and fix download

### LINKED ISSUE #648: Some required columns missing from report view
Current list includes:

Registration Date (missing from report)
Admin Policy (present online but dropped in downloaded report)

Will add to the list as I find more. Related to #627 ?

### PR DESCRIPTION
**Pull request by drh-stanford**
This PR fixes #648 and #627 by adding a registration datetime to the available reporting columns, and fixing the report field `:field` parameters such that they are all symbols and downstream expects them as such. The latter fixes the download functionality.

### CODE REVIEW

File: spec/controllers/report_controller_spec.rb [hunk 1]
```diff
@@ -61,11 +61,16 @@
   end
   describe 'download' do
     it 'should download valid CSV data' do
-      get :download
-      expect(response.status).to eq(200)
+      get :download, fields: ' '
+      expect(response).to have_http_status(:ok)
```
Comment (mejackreed) [inline spec/controllers/report_controller_spec.rb]: Nice :heart: !

**Comment by mejackreed** [comment]
It works great and looks good! Is there a simple way to add a test to see if the `Admin Policy ID` column is not omitted if future changes happen?

**Comment by drh-stanford** [comment]
Ok, I updated the spec to include the mandatory fields and whether they're on by default

**Comment by mejackreed** [comment]
Awesome!
