### PR TITLE
Set refresh to true for catkey when registering.

### LINKED ISSUE #3694: Items registered with catkeys are having the catkeys set to "do not refresh"
**Describe the bug**
When items are registered with a catkey, the catkey is being marked do not refresh. As a result no Symphony descriptive metadata is making it into the druid when the item is registered.

**User Impact**
Users do not get the metadata they need. It also presents a very confusing situation.

**To Reproduce**
1. Go to the item registration page
2. Enter a catkey when registering a druid
3. See that no Symphony metadata is ever imported.
4. See that the druid has the catkey marked as "refresh: false"

Screen Shot 2022-05-13 at 12 05 49 PM

**Expected behavior**
Druids should start with "refresh: true" when they are newly registered.

### PR DESCRIPTION
**Pull request by justinlittman**
closes #3694

## Why was this change made? 🤔
Descriptive metadata isn't being refreshed upon registration.

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact (including writing to shared file systems or interacting with other SDR APIs), ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

⚡ ⚠ If this change updates the Argo UI, run all integration tests that use Argo and create a PR on the integration test repo to fix anything this change breaks. ⚡

### CODE REVIEW

File: app/forms/registration_form.rb [hunk 1]
```diff
@@ -21,7 +21,7 @@ def cocina_model
     catalog_links = []
     if params[:other_id] != 'label:'
       catalog, record_id = params[:other_id].split(':')
-      catalog_links = [{ catalog:, catalogRecordId: record_id, refresh: false }]
+      catalog_links = [{ catalog:, catalogRecordId: record_id, refresh: true }]
     end
```
Comment (peetucket) [inline app/forms/registration_form.rb:25]: looks fine to me

**Comment by justinlittman** [comment]
Approved by Andrew.

**Review by peetucket — APPROVED** [review]
