### PR TITLE
Don't truncate error messages so short

### LINKED ISSUE #3523: Add click-to-expand functionality to display long errors in the banner message
I'm not sure if we've always done this, but error messages in the Argo page banners are being truncated. This is preventing users from being able to see the information they need to fix the issue when the later part of the message contains that information. 

Example:

truncated-error

If users could click to see the whole message it would split the difference between the long messages that contain user-facing information and the long messages that seem to be more like stack traces.

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made? 🤔
The cookie can hold up to 4k of data, so use more of that space

Fixes #3523

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact (including writing to shared file systems or interacting with other SDR APIs), ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

⚡ ⚠ If this change updates the Argo UI, run all integration tests that use Argo and create a PR on the integration test repo to fix anything this change breaks. ⚡

### CODE REVIEW

**Review by justinlittman — APPROVED** [review]

File: app/controllers/datastreams_controller.rb [hunk 1]
```diff
@@ -40,11 +40,11 @@ def update
       # if the content is not well-formed xml, inform the user rather than raising an exception
       error_msg = 'The datastream could not be saved due to malformed XML.'
     rescue Dor::Services::Client::UnexpectedResponse => e
-      error_msg = e.errors.first['detail']
+      error_msg = e.errors.first['detail']&.truncate(1024) # Truncate to avoid cookie overflow. Cookies can hold 4k.
```
Comment (justinlittman) [inline app/controllers/datastreams_controller.rb:43]: Should this be configuration?

Comment (jcoyne) [reply app/controllers/datastreams_controller.rb:43]: I find think that would just make it harder to track down.

Comment (justinlittman) [reply app/controllers/datastreams_controller.rb:43]: Yeah, but we're unlikely to remember that it needs to be changed in multiple locations. (Not a blocker, just a comment.)

Comment (jcoyne) [reply app/controllers/datastreams_controller.rb:43]: @justinlittman  it might vary by location because there is a different preamble in each place.
