### PR TITLE
Recognize parallel titles as valid titles.

### LINKED ISSUE #3600: Recognize parallel titles as valid titles when uploading the Cocina descriptive CSV (single and bulk)
**Describe the bug**
The Argo cocina descriptive spreadsheet upload appears to be rejecting CSVs with parallel titles. I'm trying to upload metadata with the following header row:

`source_id,title1.parallelValue1.structuredValue1.type,title1.parallelValue1.structuredValue1.value,title1.parallelValue1.structuredValue2.type,title1.parallelValue1.structuredValue2.value,title1.parallelValue2.value,title2.parallelValue1.type,title2.parallelValue1.value,title2.parallelValue2.type,title2.parallelValue2.value,note1.type,note1.value,purl`

This is a scaled down version of the descriptive spreadsheet you can obtain from downloading the descriptive metadata for https://argo.stanford.edu/view/gn988hy1229 I have not changed the title headers but I did remove many other columns to isolate the issue.

When I try to upload that spreadsheet I get the error "title column not found"
Screen Shot 2022-04-27 at 5 38 59 PM

**User Impact**
It's not possible to update metadata that uses parallel titles.
 
**To Reproduce**
1. Go to https://argo-stage.stanford.edu/view/druid:bc217ky7586
2. Download the cocina descriptive spreadsheet for that item
3. Upload the spreadsheet you just downloaded
4. See the error

**Expected behavior**
Parallel titles should be treated as valid.

**Additional context**
There may be other title structures that Argo needs to account for when determining validity.

### PR DESCRIPTION
**Pull request by justinlittman**
closes #3600

## Why was this change made? 🤔
Allow parallel titles, which are valid for descriptive spreadsheets.

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact (including writing to shared file systems or interacting with other SDR APIs), ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

⚡ ⚠ If this change updates the Argo UI, run all integration tests that use Argo and create a PR on the integration test repo to fix anything this change breaks. ⚡

Unit

### CODE REVIEW

File: app/services/description_validator.rb [hunk 1]
```diff
@@ -40,12 +40,13 @@ def validate_duplicate_headers
...
-      return
-    end
+    title_count = 0
+    title_count += 1 if title_value_header?
+    title_count += 1 if title_structured_value_header?
+    title_count += 1 if title_parallel_value_header?
 
-    errors << 'Title column not found.'
+    errors << 'Title column not found.' if title_count.zero?
+    errors << 'Multiple title columns found.' if title_count > 1
```
Comment (jcoyne) [inline app/services/description_validator.rb:49]: I believe multiple title columns is valid. Consider one row has a parallel title and one row has a structured title.

**Review by jcoyne — CHANGES_REQUESTED** [review]

File: app/services/description_validator.rb (hunk 1 above)
Comment (justinlittman) [reply app/services/description_validator.rb:49]: That makes sense. The previous code prevented it (notice the `exclude`) so I assumed that was intentional. Removing this check.

**Review by jcoyne — APPROVED** [review]
