### PR TITLE
fix catkey setting bulk action

### LINKED ISSUE #3591: Catkey/barcode job fails
Run by Arcadia.  BulkAction job 19178: SetCatkeysAndBarcodesJob

```
2022-04-27 16:29:23 UTC Starting SetCatkeysAndBarcodesJob for BulkAction 19178
2022-04-27 16:29:24 UTC Beginning SetCatkeysAndBarcodesJob for druid:kz765zq4441
2022-04-27 16:29:24 UTC Removing catkey
2022-04-27 16:29:24 UTC Catkey/barcode failed TypeError no implicit conversion of nil into Array
2022-04-27 16:29:25 UTC Beginning SetCatkeysAndBarcodesJob for druid:vn812jb6000
2022-04-27 16:29:25 UTC Removing catkey
2022-04-27 16:29:26 UTC Catkey/barcode failed TypeError no implicit conversion of nil into Array
2022-04-27 16:29:27 UTC Beginning SetCatkeysAndBarcodesJob for druid:my100hz2985
2022-04-27 16:29:27 UTC Removing catkey
2022-04-27 16:29:27 UTC Catkey/barcode failed TypeError no implicit conversion of nil into Array
2022-04-27 16:29:29 UTC Beginning SetCatkeysAndBarcodesJob for druid:dx448px0911
2022-04-27 16:29:29 UTC Removing catkey
2022-04-27 16:29:29 UTC Catkey/barcode failed TypeError no implicit conversion of nil into Array
2022-04-27 16:29:30 UTC Beginning SetCatkeysAndBarcodesJob for druid:vg139bb7863
2022-04-27 16:29:30 UTC Removing catkey
2022-04-27 16:29:30 UTC Catkey/barcode failed TypeError no implicit conversion of nil into Array
2022-04-27 16:29:31 UTC Beginning SetCatkeysAndBarcodesJob for druid:nr154wh5794
2022-04-27 16:29:31 UTC Removing catkey
2022-04-27 16:29:31 UTC Catkey/barcode failed TypeError no implicit conversion of nil into Array
2022-04-27 16:29:32 UTC Beginning SetCatkeysAndBarcodesJob for druid:tg571fr4496
2022-04-27 16:29:32 UTC Removing catkey
2022-04-27 16:29:32 UTC Catkey/barcode failed TypeError no implicit conversion of nil into Array
2022-04-27 16:29:34 UTC Beginning SetCatkeysAndBarcodesJob for druid:rx763bg9452
2022-04-27 16:29:34 UTC Removing catkey
2022-04-27 16:29:34 UTC Catkey/barcode failed TypeError no implicit conversion of nil into Array
2022-04-27 16:29:35 UTC Beginning SetCatkeysAndBarcodesJob for druid:yq318yc9857
2022-04-27 16:29:35 UTC Removing catkey
2022-04-27 16:29:36 UTC Catkey/barcode failed TypeError no implicit conversion of nil into Array
2022-04-27 16:29:37 UTC Beginning SetCatkeysAndBarcodesJob for druid:ss289pk3455
2022-04-27 16:29:37 UTC Removing catkey
2022-04-27 16:29:37 UTC Catkey/barcode failed TypeError no implicit conversion of nil into Array
2022-04-27 16:29:40 UTC Beginning SetCatkeysAndBarcodesJob for druid:cp997yj8157
2022-04-27 16:29:40 UTC Removing catkey
2022-04-27 16:29:40 UTC Catkey/barcode failed TypeError no implicit conversion of nil into Array
2022-04-27 16:29:43 UTC Beginning SetCatkeysAndBarcodesJob for druid:wh174bf9411
2022-04-27 16:29:43 UTC Removing catkey
2022-04-27 16:29:43 UTC Catkey/barcode failed TypeError no implicit conversion of nil into Array
2022-04-27 16:29:45 UTC Beginning SetCatkeysAndBarcodesJob for druid:jz794pm5453
2022-04-27 16:29:45 UTC Removing catkey
2022-04-27 16:29:45 UTC Catkey/barcode failed TypeError no implicit conversion of nil into Array
2022-04-27 16:29:46 UTC Beginning SetCatkeysAndBarcodesJob for druid:ty526zm1258
2022-04-27 16:29:46 UTC Removing catkey
2022-04-27 16:29:46 UTC Catkey/barcode failed TypeError no implicit conversion of nil into Array
2022-04-27 16:29:48 UTC Beginning SetCatkeysAndBarcodesJob for druid:bw926mq3879
2022-04-27 16:29:48 UTC Removing catkey
2022-04-27 16:29:48 UTC Catkey/barcode failed TypeError no implicit conversion of nil into Array
2022-04-27 16:29:49 UTC Beginning SetCatkeysAndBarcodesJob for druid:rw482mc0750
2022-04-27 16:29:49 UTC Removing catkey
2022-04-27 16:29:49 UTC Catkey/barcode failed TypeError no implicit conversion of nil into Array
2022-04-27 16:29:49 UTC Beginning SetCatkeysAndBarcodesJob for druid:fm118ts8525
2022-04-27 16:29:49 UTC Removing catkey
2022-04-27 16:29:49 UTC Catkey/barcode failed TypeError no implicit conversion of nil into Array
2022-04-27 16:29:49 UTC Finished SetCatkeysAndBarcodesJob for BulkAction 19178
```

### PR DESCRIPTION
**Pull request by peetucket**
## Why was this change made? 🤔

Fixes #3591 - removing catkeys via bulk action was not working (we need to send an empty array and not nil)

## How was this change tested? 🤨

- Tested job on stage
- New test to confirm we send a blank array and not nil when no catkey(s) are provided for a druid

### CODE REVIEW

File: app/jobs/set_catkeys_and_barcodes_job.rb [hunk 1]
```diff
@@ -23,7 +23,7 @@ def perform(bulk_action_id, params)
       update_druids.each_with_index do |current_druid, i|
         cocina_object = Repository.find(current_druid)
         args = {}
-        args[:catkeys] = catkeys[i] if catkeys
+        args[:catkeys] = (catkeys[i] || []) if catkeys
         args[:barcode] = barcodes[i] if barcodes
```
Comment (peetucket) [inline app/jobs/set_catkeys_and_barcodes_job.rb:27]: this comes in as nil if now value is set, we want it to be an empty array in that case

File: app/jobs/set_catkeys_and_barcodes_job.rb [hunk 2]
```diff
@@ -23,7 +23,7 @@ def perform(bulk_action_id, params)
       update_druids.each_with_index do |current_druid, i|
         cocina_object = Repository.find(current_druid)
         args = {}
-        args[:catkeys] = catkeys[i] if catkeys
+        args[:catkeys] = (catkeys[i] || []) if catkeys
```
Comment (jcoyne) [inline app/jobs/set_catkeys_and_barcodes_job.rb:26]:
```suggestion
        args[:catkeys] = Array(catkeys[i]) if catkeys
```

**Review by jcoyne — APPROVED** [review]
